version: '3'
services:

  postgres:
    image: postgres:13.1
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  solr:
    image: ecosis/ecosis-solr:6.6.6
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.0.5
    volumes:
      - redis-data:/data

  search:
    image: ecosis/ecosis-search:v2.0.4
    environment:
      - MONGO_HOST=mongo
      - CLIENT_ENV=prod
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "${SEARCH_HOST_PORT:-3000}:8000"

  ckan:
    image: ecosis/ecosis-data:v3.0.0
    ports:
      - "${DATA_HOST_PORT:-3001}:5000"
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-backup-data:/backup
      - ./io:/io
    env_file:
      - .env
    environment:
      - CKAN_HOME=/ckan/src
    depends_on:
      - solr
      - mongo
      - postgres

volumes:
  pg-data:
  solr-data:
  mongo-data:
  redis-data:
  ckan-data:
  ckan-backup-data:
