version: '3'
services:

  postgres:
    image: postgres:9.3
    volumes:
      - pg-data:/var/lib/postgresql/data

  solr:
    image: ecosis/ecosis-solr:5.3
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db

  search:
    image: ecosis/ecosis-search:deployment
    environment:
      - MONGO_HOST=mongo
      - CLIENT_ENV=prod
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "${SEARCH_HOST_PORT:-3000}:8000"

  ckan:
    image: ecosis/ecosis-data:deployment
    ports:
      - "${DATA_HOST_PORT:-3001}:5000"
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-backup-data:/backup
      - ./io:/io
    env_file:
      - .env
    depends_on:
      - solr
      - mongo
      - postgres

volumes:
  pg-data:
  solr-data:
  mongo-data:
  ckan-data:
  ckan-backup-data:
