version: '3'
services:

  postgres:
    image: postgres:9.3
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  solr:
    image: ecosis/ecosis-solr:5.3
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
    ports:
      - "8983:8983"

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  search:
    image: ecosis/ecosis-search:v2.0.0
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    ports:
      - "${SEARCH_HOST_PORT:-8000}:8000"

  ckan:
    image: ecosis/ecosis-data:v2.0.0
    ports:
      - "${DATA_HOST_PORT:-3001}:5000"
    volumes:
      - ckan-data:/var/lib/ckan
    depends_on:
      - solr
      - mongo
      - postgres

volumes:
  pg-data:
  solr-data:
  mongo-data:
  ckan-data:
