version: '3'
services:

  postgres:
    image: {{POSTGRES_IMAGE_NAME}}:{{POSTGRES_TAG}}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  solr:
    image: {{SOLR_IMAGE_NAME}}:{{SOLR_TAG}}
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
    ports:
      - "8983:8983"

  mongo:
    image: {{MONGO_IMAGE_NAME}}:{{MONGO_TAG}}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  search:
    image: {{SEARCH_IMAGE_NAME}}:{{SEARCH_TAG}}
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    ports:
      - "${SEARCH_HOST_PORT:-8000}:8000"

  ckan:
    image: {{DATA_IMAGE_NAME}}:{{DATA_TAG}}
    ports:
      - "${DATA_HOST_PORT:-3001}:5000"
    volumes:
      - ckan-data:/var/lib/ckan
    depends_on:
      - solr
      - mongo
      - postgres

volumes:
  pg-data:
  solr-data:
  mongo-data:
  ckan-data: