version: '3'
services:

  postgres:
    image: {{POSTGRES_IMAGE_NAME}}:{{POSTGRES_TAG}}
    volumes:
      - pg-data:/var/lib/postgresql/data

  solr:
    image: {{SOLR_IMAGE_NAME}}:{{SOLR_TAG}}
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data

  mongo:
    image: {{MONGO_IMAGE_NAME}}:{{MONGO_TAG}}
    volumes:
      - mongo-data:/data/db

  search:
    image: {{SEARCH_IMAGE_NAME}}:{{SEARCH_TAG}}
    volumes:
      - ../{{REPOSITORY_DIR}}/{{SEARCH_REPO_NAME}}/index.js:/app/index.js
      - ../{{REPOSITORY_DIR}}/{{SEARCH_REPO_NAME}}/lib:/app/lib
      - ../{{REPOSITORY_DIR}}/{{SEARCH_REPO_NAME}}/controllers:/app/controllers
      - ../{{REPOSITORY_DIR}}/{{SEARCH_REPO_NAME}}/client:/app/client
    depends_on:
      - mongo
    ports:
      - "${HOST_PORT:-3000}:3000"


volumes:
  pg-data:
  solr-data:
  mongo-data:
  ckan-data: